kind: pipeline
name: default

volumes:
  - name: cache
    temp: {}

steps:
  - name: build_dev
    image: plugins/docker
    volumes:
      - name: cache
        path: /var/lib/docker
    settings:
      tags:
        - 'dev-env_${DRONE_COMMIT_SHA:0:7}'
        - dev-env
      repo: uccnetsoc/netsoc.co
      target: dev
      registry: docker.io
      username:
        from_secret: docker_hub_user
      password:
        from_secret: docker_hub_token
    when:
      event:
        - push
      branch:
        - master

  - name: build_prod
    image: plugins/docker
    volumes:
      - name: cache
        path: /var/lib/docker
    settings:
      tags:
        - '${DRONE_COMMIT_SHA:0:7}'
        - new
        - latest
      repo: uccnetsoc/netsoc.co
      registry: docker.io
      username:
        from_secret: docker_hub_user
      password:
        from_secret: docker_hub_token
    when:
      event:
        - push
      branch:
        - master
        
  - name: clone_nac
    image: docker:git
    commands:
      - git clone https://github.com/UCCNetsoc/NaC.git .ansible
      - mkdir -p ./keys/infra/web/
      - mkdir -p ./keys/infra/databases/
      - printf '%s\n' "$KEY_WEB" >./keys/infra/web/id_rsa
      - printf '%s\n' "$KEY_DATABASES" >./keys/infra/databases/id_rsa
      - chmod 0600 ./keys/infra/web/id_rsa
      - chmod 0600 ./keys/infra/databases/id_rsa
      - ls -al ./keys/infra/web
      - ls -al ./keys/infra/databases
    environment:
      KEY_WEB:
        from_secret: key_web
      KEY_DATABASES:
        from_secret: key_databases
    when:
      event:
        - push
      branch:
        - master

  - name: ansible_deploy
    image: uccnetsoc/drone-ansible
    environment:
      PM_HOST: '10.0.30.53'
      PM_USER:
        from_secret: proxmox_user
      PM_PASS:
        from_secret: proxmox_pass
      VAULT_PASS:
        from_secret: vault_pass
    settings:
      playbook: .ansible/provision-infra-web.yml
      requirements: .ansible/requirements.txt
      inventory: .ansible/proxmox_inventory.py
      private_key:
        from_secret: key_web
      vault_password:
        from_secret: vault_pass
      tags:
        - static-websites
    when:
      event:
        - push
      branch:
        - master
        
  - name: discord_notif_success
    image: appleboy/drone-discord
    environment:
      WEBHOOK_ID:
        from_secret: discord_webhook_id
      WEBHOOK_TOKEN:
        from_secret: discord_webhook_token
    settings:
      username: Netsoc CI
      avatar_url: https://raw.githubusercontent.com/drone/brand/3051b0d85318a2a20b62927ba19fc07e24c0d751/logos/png/white/drone-logo-png-white-256.png
      color: '#42f483'
      message: netsoc.co new_website successfully built and pushed. Build num {{build.number}}. {{build.link}}
    when:
      event:
        - push
      branch:
        - master
      status:
        - success
        
  - name: discord_notif_failure
    image: appleboy/drone-discord
    environment:
      WEBHOOK_ID:
        from_secret: discord_webhook_id
      WEBHOOK_TOKEN:
        from_secret: discord_webhook_token
    settings:
      username: Netsoc CI
      avatar_url: https://raw.githubusercontent.com/drone/brand/3051b0d85318a2a20b62927ba19fc07e24c0d751/logos/png/white/drone-logo-png-white-256.png
      color: '#e04414'
      message: netsoc.co failed for {{build.author}}. Build num {{build.number}}. {{build.link}}
    when:
      event:
        - push
      branch:
        - master
      status:
        - failure
